# Windows Rules

# Float Necessary Windows
windowrule = float on, match:class (org.pulseaudio.pavucontrol)
windowrule = float on, match:title (Picture in picture)
windowrule = float on, match:title (Save File)
windowrule = float on, match:title (Open File)
windowrule = float on, match:class (LibreWolf)
windowrule = float on, match:class (blueman-manager)
windowrule = float on, match:class (xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)
windowrule = float on, match:class (polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)
windowrule = float on, match:class (CachyOSHello)
windowrule = float on, match:class (zenity)
windowrule = float on, match:title (Steam - Self Updater)

# Opacity rules
windowrule = opacity 0.92, match:class (thunar|nemo)
windowrule = opacity 0.96, match:class (discord|armcord|webcord)
windowrule = opacity 0.95, match:title (QQ|Telegram)
windowrule = opacity 0.95, match:title (NetEase Cloud Music Gtk4)

# General window rules
windowrule = float on, match:title (Picture-in-Picture)
windowrule = size 960 540, match:title (Picture-in-Picture)
windowrule = move 25%-, match:title (Picture-in-Picture)
windowrule = float on, match:title (imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)
windowrule = move 25%-, match:title (imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)
windowrule = size 960 540, match:title (imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)
windowrule = pin on, match:title (danmufloat)
windowrule = rounding 5, match:title (danmufloat|termfloat)
windowrule = no_blur on, match:class (org.mozilla.firefox)

# Workspace Rules
workspace = 1, gapsout:5, gapsin:3
workspace = 2, gapsout:5, gapsin:3
workspace = 3, gapsout:5, gapsin:3
workspace = 4, gapsout:5, gapsin:3
workspace = 5, gapsout:5, gapsin:3
workspace = 6, gapsout:5, gapsin:3
workspace = 7, gapsout:5, gapsin:3
workspace = 8, gapsout:5, gapsin:3
workspace = 9, gapsout:5, gapsin:3
workspace = 10, gapsout:5, gapsin:3
